config/routes.rb
Webboard::Application.routes.draw do
  get "forum/index"

  resources :posts do
    resources :comments
  end
    

  root :to => "forum#index", :as => "forum"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  
  validates :body, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  
  validates :title, :body, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # POST /comments
  # POST /comments.xml
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    redirect_to @post
  end

end

app/controllers/forum_controller.rb
class ForumController < ApplicationController
  def index
    @posts = Post.order("created_at DESC")
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate, :except => [:index, :show, :new]
  
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.order("created_at DESC")

    respond_to do |format|
      format.html { redirect_to forum_url }
      format.xml  { render :xml => @posts }
      format.atom # index.atom.builder
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to forum_url }
      format.xml  { head :ok }
    end
  end
  
  private
  
    def authenticate
      authenticate_or_request_with_http_basic do |name, password|
        name == "admin" && password == "secret"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/forum_helper.rb
module ForumHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/forum/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h2>Forum: 15-minute webboard showcase</h2>
<p>This is a demo of building a webboard in 15 minutes using Rails 3.</p>

<table class="forum">
  <tr>
    <th></th>
    <th>Post / Title</th>
    <th>Replies</th>
    <th>Post by</th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><div class="big_letter">?</div></td>
    <td>      
      <%= link_to post do %>
        <strong><%= post.title %></strong>
      <% end %><br />
      <%= truncate strip_tags(post.body), :length => 60 %>
    </td>
    <td>Replies: <%= post.comments.count %></td>
    <td></td>
  </tr>
<% end %>
</table>

<p><%= link_to '+ Post New', new_post_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>15-min webboard&trade;</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= auto_discovery_link_tag :atom, posts_path(:atom) %>
</head>
<body>

<div id="wrap">

  <div id="header">
    <h1>15-min webboard&trade;</h1>
  </div>
  
  <div id="nav">
    <p><%= link_to 'Forum', forum_path %> | <%= link_to 'Register' %> | <%= link_to 'Help' %></p>
  </div>

  <div id="content">
  <%= yield %>
  </div>

  <div id="footer">
    <p>
      Powered by 15-min webboard&trade; Version 0.1<br />
      Copyright &copy; Weera Wu. All rights reserved.
    </p>
  </div>
  
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :size => "65" %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, :size => "50x10" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit post</h2>

<%= render 'form' %>

app/views/posts/new.html.erb
<h2>New post</h2>

<%= render 'form' %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Post: <%= @post.title %></h2>

<table class="post">
  <tr>
    <th colspan="2">
      <div class="time">
        Posted <%= time_ago_in_words @post.created_at.in_time_zone('Bangkok') %> ago
      </div>
      <div class="action">
        <%= link_to 'Edit', edit_post_path(@post) %> | 
        <%= link_to 'Destroy', @post, :confirm => 'Are you sure?', :method => :delete %>
      </div>
    </th>
  </tr>
  
  <tr>
    <td><div class="big_letter">?{</div></td>
    <td>
      <div class="post_body">
        <%= simple_format sanitize(@post.body) %>
      </div>
    </td>
  </tr>
  
<% @post.comments.each do |comment| %>
  <tr>
    <th colspan="2">
      <div class="time">
        Posted <%= time_ago_in_words comment.created_at.in_time_zone('Bangkok') %> ago
      </div>
    </th>
  </tr>
  
  <tr>
    <td><div class="big_letter">r{</div></td>
    <td>
      <div class="post_body">
        <%= simple_format sanitize(comment.body) %>
      </div>
    </td>
  </tr>
<% end %>

<%= form_for [@post, Comment.new] do |f| %>
  <tr>
    <th colspan="2"><div class="time"><%= Time.now.in_time_zone('Bangkok').strftime("%d/%m/%Y %H:%M") %></th>
  </tr>
  
  <tr>
    <td><div class="big_letter">r{</div></td>
    <td>
      <%= f.text_area :body, :size => "60x6" %><br />
      <%= f.submit "Submit" %>
    </td>
  </tr>
<% end %>

</table>